{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "911-training.frontend.labels" . | nindent 4 }}
data:
  VITE_API_URL: {{ .Values.frontend.config.viteApiUrl | quote }}
  VITE_WS_URL: {{ .Values.frontend.config.viteWsUrl | quote }}
{{- end }}
