{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "911-training.postgresql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
  - name: postgresql
    port: {{ .Values.postgresql.service.port }}
    targetPort: {{ .Values.postgresql.service.port }}
    protocol: TCP
  selector:
    {{- include "911-training.postgresql.selectorLabels" . | nindent 4 }}
  clusterIP: None
{{- end }}
