{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "911-training.redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
  - name: redis
    port: {{ .Values.redis.service.port }}
    targetPort: {{ .Values.redis.service.port }}
    protocol: TCP
  selector:
    {{- include "911-training.redis.selectorLabels" . | nindent 4 }}
{{- end }}
